apiVersion: v1
kind: Pod
metadata:
  name: 1stbuildpod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: newsecrets
      mountPath: "/etc/newsecrets"
      readOnly: true
  volumes:
  - name: newsecrets
    secret:
      secretName: newsecrets
